on: [push]
name: Linux_Container_Workflow
# test update
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
            AWS_ACCESS_KEY: ${{ secrets.AWS_S3_ACCESS_KEY }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/yt-dl-client:latest
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/yt-dl-client:latest
